import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { Table, Button } from 'react-bootstrap'
import { useRouter } from 'next/router';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container h-100vh">
        <div className="d-flex justify-content-center align-items-center h-100vh">
          <Table striped bordered hover className='align-middle'>
            <tbody>
              <tr>
                <td className='d-flex justify-content-center'><Button onClick={() => window.open("https://www.linkedin.com/in/ozdemirdev/", "_blank")}>Linkedin</Button></td>
              </tr>
              <tr>
                <td className='d-flex justify-content-center'><Button onClick={() => window.open("https://github.com/ozdemirdev/dummyApiNextJS", "_blank")}>Github Repo</Button></td>
              </tr>
              <tr>
                <td className='d-flex justify-content-center'><Button  className='btn btn-success' onClick={() => router.push('/posts')}>Inspect Project</Button></td>
              </tr>
            </tbody>
          </Table>
        </div>
      </div>

    </>
  )
}
